### PR TITLE
Fixed "Invalid capture template" like that.

### PR DESCRIPTION
**Pull request by believerd**

### CODE REVIEW

**Comment by rougier** [comment]
Thanks (forgot about my reply in the issue, I did not see the PR). I think the reason it does not work is an extra `)`. Would you mind just removing the extra `)` in your fix ? I tend to ind i more clear when  templates are split over several lines.

**Comment by believerd** [comment]
Thanks for your reply but it is not about the `)`. See the new commit. It should be working, still using "concat".

**Comment by believerd** [comment]
What I did is using a "backquote" and add a "comma" before concat.

**Comment by rougier** [comment]
Many thanks. I'm far from mastering elisp and always got problems as when (and why) to use quote backquote and comma...

**Pull request merged**
