### PR TITLE
Added `automatic saving after refilling` section rougier/emacs-gtd/#9

### PR DESCRIPTION
**Pull request by KirmTwinty**
Added a new section for including the code referenced in #9.

Not really sure where I had to put it, let me know if you prefer it to be somewhere else.

### CODE REVIEW

**Comment by rougier** [comment]
Thansk !

**Comment by rougier** [comment]
It's online.

**Comment by KirmTwinty** [comment]
Thank you!
I did not generate the HTML though.

**Comment by rougier** [comment]
I did.

**Pull request merged**
